export const jobData = [
    {
      companyName: "XYZ Tech",
      jobTitle: "Software Engineer",
      location: "San Francisco",
      jobField: "Engineering",
      experienceRequired: 5,
      jobType: "Full Time",
      salaryOffered: 90000,
      created: 1680508800,
      jobDetail: "Join our engineering team to develop cutting-edge software solutions.",
      skills: ["JavaScript", "React", "Node.js"],
      category: "Engineering",
    },
    {
      companyName: "HealthCare Innovators",
      jobTitle: "Registered Nurse",
      location: "Chicago",
      jobField: "Health & Care",
      experienceRequired: 2,
      jobType: "Part Time",
      salaryOffered: 50000,
      created: 1680864000,
      jobDetail: "Join our healthcare team to provide quality patient care and support.",
      skills: ["Nursing", "Patient Care", "Communication"],
      category: "Health & Care",
    },
    {
      companyName: "E-Commerce Emporium",
      jobTitle: "Accountant",
      location: "Los Angeles",
      jobField: "Accountancy",
      experienceRequired: 4,
      jobType: "Freelance",
      salaryOffered: 60000,
      created: 1681152000,
      jobDetail: "Join our finance team to manage accounts and financial transactions.",
      skills: ["Accounting", "Financial Analysis", "Bookkeeping"],
      category: "Accountancy",
    },
    {
    companyName: "Tech Innovators",
    jobTitle: "Data Scientist",
    location: "Seattle",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 85000,
    created: 1681555200,
    jobDetail: "Join our data science team to analyze and interpret complex data sets.",
    skills: ["Machine Learning", "Python", "Statistical Analysis"],
    category: "Engineering",
  },
  {
    companyName: "Marketing Maven",
    jobTitle: "Digital Marketing Specialist",
    location: "Austin",
    jobField: "Marketing",
    experienceRequired: 2,
    jobType: "Temporary",
    salaryOffered: 60000,
    created: 1681862400,
    jobDetail: "Join our digital marketing team to execute online marketing campaigns.",
    skills: ["SEO", "Social Media Management", "Email Marketing"],
    category: "Sales & Marketing",
  },
  {
    companyName: "GreenTech Solutions",
    jobTitle: "Environmental Engineer",
    location: "Denver",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 95000,
    created: 1682246400,
    jobDetail: "Join our environmental engineering team to work on sustainable solutions.",
    skills: ["Environmental Engineering", "Renewable Energy", "Climate Modeling"],
    category: "Engineering",
  },
  {
    companyName: "Finance Experts Ltd",
    jobTitle: "Financial Analyst",
    location: "Chicago",
    jobField: "Accountancy",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 75000,
    created: 1682563200,
    jobDetail: "Join our finance team to analyze financial data and provide insights.",
    skills: ["Financial Analysis", "Budgeting", "Excel"],
    category: "Accountancy",
  },
  {
    companyName: "Creative Ventures Inc",
    jobTitle: "Graphic Designer",
    location: "Los Angeles",
    jobField: "Sales & Marketing",
    experienceRequired: 2,
    jobType: "Part Time",
    salaryOffered: 55000,
    created: 1682928000,
    jobDetail: "Join our creative team to design visually appealing graphics and marketing materials.",
    skills: ["Graphic Design", "Adobe Creative Suite", "UI/UX"],
    category: "Sales & Marketing",
  },
  {
    companyName: "Tech Support Solutions",
    jobTitle: "IT Support Specialist",
    location: "New York",
    jobField: "Engineering",
    experienceRequired: 4,
    jobType: "Freelance",
    salaryOffered: 70000,
    created: 1683244800,
    jobDetail: "Join our IT support team to assist users with technical issues and troubleshooting.",
    skills: ["Technical Support", "Networking", "Troubleshooting"],
    category: "Engineering",
  },
  {
    companyName: "Tech Innovators",
    jobTitle: "Data Scientist",
    location: "Bangalore, India",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 85000,
    created: 1681555200,
    jobDetail: "Join our data science team to analyze and interpret complex data sets.",
    skills: ["Machine Learning", "Python", "Statistical Analysis"],
    category: "Engineering",
  },
  {
    companyName: "Digital Solutions Pvt Ltd",
    jobTitle: "Software Developer",
    location: "Mumbai, India",
    jobField: "Engineering",
    experienceRequired: 2,
    jobType: "Temporary",
    salaryOffered: 60000,
    created: 1681862400,
    jobDetail: "Join our software development team to build innovative applications.",
    skills: ["JavaScript", "React", "Node.js"],
    category: "Engineering",
  },
  {
    companyName: "HealthCare Innovators",
    jobTitle: "Medical Officer",
    location: "Delhi, India",
    jobField: "Health & Care",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 70000,
    created: 1682246400,
    jobDetail: "Join our healthcare team to provide medical care and support.",
    skills: ["Medical Practice", "Patient Care", "Health Assessment"],
    category: "Health & Care",
  },
  {
    companyName: "E-Commerce Hub",
    jobTitle: "E-Commerce Manager",
    location: "Hyderabad, India",
    jobField: "Sales & Marketing",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 80000,
    created: 1682563200,
    jobDetail: "Lead our e-commerce initiatives and drive online sales growth.",
    skills: ["E-Commerce Management", "Digital Marketing", "Market Analysis"],
    category: "Sales & Marketing",
  },
  {
    companyName: "GreenTech Solutions",
    jobTitle: "Environmental Scientist",
    location: "Chennai, India",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Part Time",
    salaryOffered: 90000,
    created: 1682928000,
    jobDetail: "Contribute to environmental research and sustainable development projects.",
    skills: ["Environmental Science", "Research", "Data Analysis"],
    category: "Engineering",
  },
  {
    companyName: "Financial Insights Ltd",
    jobTitle: "Chartered Accountant",
    location: "Pune, India",
    jobField: "Accountancy",
    experienceRequired: 6,
    jobType: "Freelance",
    salaryOffered: 100000,
    created: 1683244800,
    jobDetail: "Provide financial advice, audit accounts, and offer strategic financial insights.",
    skills: ["Chartered Accountancy", "Financial Planning", "Audit"],
    category: "Accountancy",
  },
  {
    companyName: "Tech Solutions India",
    jobTitle: "Java Developer",
    location: "Bengaluru, India",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 75000,
    created: 1683676800,
    jobDetail: "Join our Java development team to build scalable and efficient applications.",
    skills: ["Java", "Spring Framework", "Database Management"],
    category: "Engineering",
  },
  {
    companyName: "Health & Wellness Clinic",
    jobTitle: "Nutritionist",
    location: "Mumbai, India",
    jobField: "Health & Care",
    experienceRequired: 2,
    jobType: "Temporary",
    salaryOffered: 55000,
    created: 1683993600,
    jobDetail: "Provide nutritional counseling and support to clients for a healthier lifestyle.",
    skills: ["Nutrition Counseling", "Diet Planning", "Health Education"],
    category: "Health & Care",
  },
  {
    companyName: "Tech Start Innovate",
    jobTitle: "UI/UX Designer",
    location: "Delhi, India",
    jobField: "Sales & Marketing",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 90000,
    created: 1684348800,
    jobDetail: "Design intuitive and visually appealing user interfaces for web and mobile applications.",
    skills: ["UI Design", "UX Research", "Prototyping"],
    category: "Sales & Marketing",
  },
  {
    companyName: "Tech Innovators",
    jobTitle: "Data Scientist",
    location: "New York, USA",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 95000,
    created: 1684857600,
    jobDetail: "Join our data science team to analyze and interpret complex data sets.",
    skills: ["Machine Learning", "Python", "Statistical Analysis"],
    category: "Engineering",
  },
  {
    companyName: "Digital Solutions Ltd",
    jobTitle: "Web Developer",
    location: "London, UK",
    jobField: "Engineering",
    experienceRequired: 2,
    jobType: "Temporary",
    salaryOffered: 65000,
    created: 1685241600,
    jobDetail: "Join our web development team to create interactive and responsive websites.",
    skills: ["HTML", "CSS", "JavaScript"],
    category: "Engineering",
  },
  {
    companyName: "Global HealthCare Solutions",
    jobTitle: "Medical Researcher",
    location: "Toronto, Canada",
    jobField: "Health & Care",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 85000,
    created: 1685635200,
    jobDetail: "Contribute to medical research projects for advancements in healthcare.",
    skills: ["Medical Research", "Data Analysis", "Clinical Studies"],
    category: "Health & Care",
  },
  {
    companyName: "Tech Innovate GmbH",
    jobTitle: "Software Architect",
    location: "Berlin, Germany",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 100000,
    created: 1686000000,
    jobDetail: "Lead the architecture and design of software systems for innovative projects.",
    skills: ["Software Architecture", "Java", "Cloud Computing"],
    category: "Engineering",
  },
  {
    companyName: "Digital Marketing Pros",
    jobTitle: "SEO Specialist",
    location: "Sydney, Australia",
    jobField: "Sales & Marketing",
    experienceRequired: 3,
    jobType: "Freelance",
    salaryOffered: 80000,
    created: 1686403200,
    jobDetail: "Optimize websites for search engines to improve organic search visibility.",
    skills: ["SEO", "Keyword Research", "Analytics"],
    category: "Sales & Marketing",
  },
  {
    companyName: "Finance Experts Inc",
    jobTitle: "Financial Planner",
    location: "Tokyo, Japan",
    jobField: "Accountancy",
    experienceRequired: 6,
    jobType: "Full Time",
    salaryOffered: 120000,
    created: 1686816000,
    jobDetail: "Provide comprehensive financial planning services to clients for their financial goals.",
    skills: ["Financial Planning", "Investment Management", "Risk Analysis"],
    category: "Accountancy",
  },
  {
    companyName: "Tech Innovate SA",
    jobTitle: "UX/UI Designer",
    location: "Cape Town, South Africa",
    jobField: "Engineering",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 90000,
    created: 1687209600,
    jobDetail: "Design user interfaces and experiences for web and mobile applications.",
    skills: ["UX Design", "UI Design", "Prototyping"],
    category: "Engineering",
  },
  {
    companyName: "E-Commerce Solutions",
    jobTitle: "Product Manager",
    location: "Singapore",
    jobField: "Sales & Marketing",
    experienceRequired: 5,
    jobType: "Part Time",
    salaryOffered: 110000,
    created: 1687564800,
    jobDetail: "Lead the product development process and drive business growth.",
    skills: ["Product Management", "Market Analysis", "Product Strategy"],
    category: "Sales & Marketing",
  },
  {
    companyName: "HealthCare Innovate",
    jobTitle: "Physiotherapist",
    location: "Dubai, UAE",
    jobField: "Health & Care",
    experienceRequired: 3,
    jobType: "Temporary",
    salaryOffered: 80000,
    created: 1687948800,
    jobDetail: "Provide physiotherapy services and support patients in their rehabilitation journey.",
    skills: ["Physiotherapy", "Rehabilitation", "Patient Care"],
    category: "Health & Care",
  },
  {
    companyName: "Tech Solutions",
    jobTitle: "Cybersecurity Analyst",
    location: "Tel Aviv, Israel",
    jobField: "Engineering",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 95000,
    created: 1688332800,
    jobDetail: "Protect our organization's systems and networks from cyber threats.",
    skills: ["Cybersecurity", "Network Security", "Incident Response"],
    category: "Engineering",
  },
  {
    companyName: "Digital Agency Pro",
    jobTitle: "Content Writer",
    location: "Paris, France",
    jobField: "Sales & Marketing",
    experienceRequired: 2,
    jobType: "Freelance",
    salaryOffered: 60000,
    created: 1688716800,
    jobDetail: "Create engaging and SEO-friendly content for websites and marketing materials.",
    skills: ["Content Writing", "SEO Optimization", "Copywriting"],
    category: "Sales & Marketing",
  },
  {
    companyName: "Finance Excellence",
    jobTitle: "Internal Auditor",
    location: "Frankfurt, Germany",
    jobField: "Accountancy",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 100000,
    created: 1689100800,
    jobDetail: "Conduct internal audits to assess financial controls and compliance.",
    skills: ["Internal Auditing", "Risk Management", "Financial Reporting"],
    category: "Accountancy",
  },
  {
    companyName: "Tech Ventures",
    jobTitle: "Machine Learning Engineer",
    location: "Seoul, South Korea",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Temporary",
    salaryOffered: 80000,
    created: 1689484800,
    jobDetail: "Work on cutting-edge machine learning projects to advance technology.",
    skills: ["Machine Learning", "Python", "Deep Learning"],
    category: "Engineering",
  },
  {
    companyName: "Digital Innovations",
    jobTitle: "Social Media Manager",
    location: "São Paulo, Brazil",
    jobField: "Sales & Marketing",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 90000,
    created: 1689868800,
    jobDetail: "Manage social media presence and campaigns to enhance brand visibility.",
    skills: ["Social Media Management", "Content Strategy", "Analytics"],
    category: "Sales & Marketing",
  },
  {
    companyName: "HealthTech Solutions",
    jobTitle: "Medical Transcriptionist",
    location: "Mumbai, India",
    jobField: "Health & Care",
    experienceRequired: 2,
    jobType: "Part Time",
    salaryOffered: 50000,
    created: 1690252800,
    jobDetail: "Transcribe medical records and documents accurately for healthcare providers.",
    skills: ["Medical Transcription", "Attention to Detail", "Medical Terminology"],
    category: "Health & Care",
  },
  {
    companyName: "Finance Dynamics",
    jobTitle: "Financial Analyst",
    location: "Toronto, Canada",
    jobField: "Accountancy",
    experienceRequired: 3,
    jobType: "Freelance",
    salaryOffered: 70000,
    created: 1690636800,
    jobDetail: "Analyze financial data and provide insights for informed decision-making.",
    skills: ["Financial Analysis", "Excel", "Budgeting"],
    category: "Accountancy",
  },
  {
    companyName: "GreenTech Solutions",
    jobTitle: "Environmental Consultant",
    location: "Copenhagen, Denmark",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 110000,
    created: 1691020800,
    jobDetail: "Provide expertise in environmental issues and sustainable solutions.",
    skills: ["Environmental Consulting", "Regulatory Compliance", "Sustainability"],
    category: "Engineering",
  },
  {
    companyName: "Tech Solutions SG",
    jobTitle: "Software Tester",
    location: "Singapore",
    jobField: "Engineering",
    experienceRequired: 2,
    jobType: "Full Time",
    salaryOffered: 60000,
    created: 1691404800,
    jobDetail: "Test software applications for quality assurance and identify bugs.",
    skills: ["Software Testing", "Quality Assurance", "Test Automation"],
    category: "Engineering",
  },
  {
    companyName: "Creative Agency London",
    jobTitle: "Graphic Design Intern",
    location: "London, UK",
    jobField: "Sales & Marketing",
    experienceRequired: 0,
    jobType: "Internship",
    salaryOffered: 30000,
    created: 1691788800,
    jobDetail: "Assist in creating visually appealing graphics for marketing materials.",
    skills: ["Graphic Design", "Adobe Creative Suite", "Creativity"],
    category: "Sales & Marketing",
  },
  {
    companyName: "Global HealthCare Solutions",
    jobTitle: "Registered Dietitian",
    location: "New York, USA",
    jobField: "Health & Care",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 75000,
    created: 1692172800,
    jobDetail: "Provide dietary advice and support for patients' health and well-being.",
    skills: ["Nutrition", "Dietetics", "Patient Counseling"],
    category: "Health & Care",
  },
  {
    companyName: "Finance Pros Sydney",
    jobTitle: "Tax Consultant",
    location: "Sydney, Australia",
    jobField: "Accountancy",
    experienceRequired: 4,
    jobType: "Part Time",
    salaryOffered: 85000,
    created: 1692556800,
    jobDetail: "Assist clients in tax planning and compliance with tax regulations.",
    skills: ["Taxation", "Financial Consulting", "Legal Compliance"],
    category: "Accountancy",
  },
  {
    companyName: "GreenTech Innovate",
    jobTitle: "Renewable Energy Engineer",
    location: "Berlin, Germany",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 100000,
    created: 1692940800,
    jobDetail: "Contribute to the development of sustainable and renewable energy solutions.",
    skills: ["Renewable Energy", "Solar Power", "Engineering Design"],
    category: "Engineering",
  },
  {
    companyName: "Tech Innovations Tokyo",
    jobTitle: "AI Research Scientist",
    location: "Tokyo, Japan",
    jobField: "Engineering",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 120000,
    created: 1693324800,
    jobDetail: "Lead AI research projects to push the boundaries of artificial intelligence.",
    skills: ["Artificial Intelligence", "Machine Learning", "Research"],
    category: "Engineering",
  },
  {
    companyName: "Digital Marketing Wizards",
    jobTitle: "Email Marketing Specialist",
    location: "Toronto, Canada",
    jobField: "Sales & Marketing",
    experienceRequired: 3,
    jobType: "Freelance",
    salaryOffered: 70000,
    created: 1693708800,
    jobDetail: "Develop and execute effective email marketing campaigns for client success.",
    skills: ["Email Marketing", "Marketing Automation", "Copywriting"],
    category: "Sales & Marketing",
  },
  {
    companyName: "HealthCare Innovate Dubai",
    jobTitle: "Clinical Psychologist",
    location: "Dubai, UAE",
    jobField: "Health & Care",
    experienceRequired: 6,
    jobType: "Full Time",
    salaryOffered: 110000,
    created: 1694092800,
    jobDetail: "Provide psychological assessments and therapeutic interventions for patients.",
    skills: ["Clinical Psychology", "Therapy", "Counseling"],
    category: "Health & Care",
  },
  {
    companyName: "Finance Experts São Paulo",
    jobTitle: "Forensic Accountant",
    location: "São Paulo, Brazil",
    jobField: "Accountancy",
    experienceRequired: 4,
    jobType: "Part Time",
    salaryOffered: 90000,
    created: 1694476800,
    jobDetail: "Investigate financial discrepancies and provide expert testimony in legal cases.",
    skills: ["Forensic Accounting", "Investigation", "Legal Compliance"],
    category: "Accountancy",
  },
  {
    companyName: "GreenTech Innovations Paris",
    jobTitle: "Sustainability Analyst",
    location: "Paris, France",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Temporary",
    salaryOffered: 80000,
    created: 1694860800,
    jobDetail: "Assess and implement sustainability initiatives for environmental conservation.",
    skills: ["Sustainability", "Environmental Analysis", "Project Management"],
    category: "Engineering",
  },
  {
    companyName: "Tech Innovate Seoul",
    jobTitle: "DevOps Engineer",
    location: "Seoul, South Korea",
    jobField: "Engineering",
    experienceRequired: 4,
    jobType: "Full Time",
    salaryOffered: 90000,
    created: 1695244800,
    jobDetail: "Implement and manage DevOps practices to enhance software development and delivery.",
    skills: ["DevOps", "Continuous Integration", "Containerization"],
    category: "Engineering",
  },
  {
    companyName: "Digital Marketing Sydney",
    jobTitle: "Social Media Strategist",
    location: "Sydney, Australia",
    jobField: "Sales & Marketing",
    experienceRequired: 3,
    jobType: "Freelance",
    salaryOffered: 75000,
    created: 1695628800,
    jobDetail: "Develop and execute social media strategies to increase brand awareness.",
    skills: ["Social Media Strategy", "Campaign Planning", "Analytics"],
    category: "Sales & Marketing",
  },
  {
    companyName: "HealthCare Excellence London",
    jobTitle: "Occupational Therapist",
    location: "London, UK",
    jobField: "Health & Care",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 100000,
    created: 1696012800,
    jobDetail: "Provide therapeutic interventions to help individuals achieve independence in daily activities.",
    skills: ["Occupational Therapy", "Rehabilitation", "Patient Care"],
    category: "Health & Care",
  },
  {
    companyName: "Finance Dynamics Berlin",
    jobTitle: "Risk Analyst",
    location: "Berlin, Germany",
    jobField: "Accountancy",
    experienceRequired: 3,
    jobType: "Part Time",
    salaryOffered: 70000,
    created: 1696396800,
    jobDetail: "Analyze financial data and assess potential risks for effective risk management.",
    skills: ["Risk Analysis", "Financial Modeling", "Regulatory Compliance"],
    category: "Accountancy",
  },
  {
    companyName: "GreenTech Solutions Tokyo",
    jobTitle: "Renewable Energy Consultant",
    location: "Tokyo, Japan",
    jobField: "Engineering",
    experienceRequired: 6,
    jobType: "Temporary",
    salaryOffered: 120000,
    created: 1696780800,
    jobDetail: "Consult on renewable energy projects and contribute to sustainable solutions.",
    skills: ["Renewable Energy", "Consulting", "Environmental Impact Assessment"],
    category: "Engineering",
  },
  {
    companyName: "Tech Innovations Mumbai",
    jobTitle: "Blockchain Developer",
    location: "Mumbai, India",
    jobField: "Engineering",
    experienceRequired: 3,
    jobType: "Full Time",
    salaryOffered: 80000,
    created: 1697164800,
    jobDetail: "Contribute to the development of blockchain solutions for secure and transparent transactions.",
    skills: ["Blockchain Development", "Smart Contracts", "Decentralized Applications"],
    category: "Engineering",
  },
  {
    companyName: "Digital Marketing Barcelona",
    jobTitle: "Content Marketing Manager",
    location: "Barcelona, Spain",
    jobField: "Sales & Marketing",
    experienceRequired: 4,
    jobType: "Freelance",
    salaryOffered: 85000,
    created: 1697548800,
    jobDetail: "Lead content marketing strategies to drive brand engagement and lead generation.",
    skills: ["Content Marketing", "SEO", "Content Strategy"],
    category: "Sales & Marketing",
  },
  {
    companyName: "HealthCare Solutions Paris",
    jobTitle: "Speech-Language Pathologist",
    location: "Paris, France",
    jobField: "Health & Care",
    experienceRequired: 5,
    jobType: "Full Time",
    salaryOffered: 95000,
    created: 1697932800,
    jobDetail: "Provide speech therapy services to individuals with communication disorders.",
    skills: ["Speech-Language Pathology", "Communication Disorders", "Patient Care"],
    category: "Health & Care",
  },
  {
    companyName: "Finance Pros Amsterdam",
    jobTitle: "Senior Tax Advisor",
    location: "Amsterdam, Netherlands",
    jobField: "Accountancy",
    experienceRequired: 6,
    jobType: "Part Time",
    salaryOffered: 110000,
    created: 1698316800,
    jobDetail: "Advise clients on tax planning strategies and compliance with tax regulations.",
    skills: ["Tax Advisory", "Financial Planning", "Legal Compliance"],
    category: "Accountancy",
  },
  {
    companyName: "GreenTech Innovations Singapore",
    jobTitle: "Environmental Scientist",
    location: "Singapore",
    jobField: "Engineering",
    experienceRequired: 4,
    jobType: "Temporary",
    salaryOffered: 90000,
    created: 1698700800,
    jobDetail: "Conduct research and analysis to address environmental challenges and sustainability.",
    skills: ["Environmental Science", "Research", "Data Analysis"],
    category: "Engineering",
  },

  ];